-- Run once in the Supabase SQL editor after checking the target project.
-- Keep StoreApi tables outside the schemas exposed through the Data API.
create schema if not exists store;

create table if not exists store.books (
    id integer generated by default as identity primary key,
    title text not null check (length(trim(title)) > 0),
    author text not null check (length(trim(author)) > 0)
);
